workflows:
  flutter-quiz-ci:
    name: Flutter Quiz CI
    max_build_duration: 10
    environment:
      flutter: stable
      vars:
        BUILD_TYPE: debug
    scripts:

      - flutter pub get

      - flutter analyze


      - flutter test


      - flutter build apk --debug

    artifacts:

      - build/app/outputs/flutter-apk/app-debug.apk
